### ISSUE TITLE
Esse método é pra ser privado?

### ISSUE THREAD

**Issue by zabaala** [andersonn-roberto/laravel-sso-test#1]
https://github.com/andersonn-roberto/laravel-sso-test/blob/2e9205bad0cda82d34fa8e5eb13e28b6fdfbee75/client/app/Client1Broker.php#L66

**Comment by zabaala** [comment]
Deve ser público ;)

**Comment by andersonn-roberto** [comment]
@zabaala Desculpe reviver isso, mas voltei a mexer nessa parada de SSO e acontece o seguinte, eu entro em um sistema e faço login, quando vou para um segundo sistema ele exibe o formulário de login, porém, basta dar refresh na página para que ele entre no segundo sistema. Penso que tenho que fazer alguma coisa para que o usuário entre automaticamente em um sistema caso tenha feito login em outro, mas não tenho ideia de onde e o que fazer.
