### ISSUE TITLE
Tenta rodar um dd($myBroker) aqui, chamando qualquer método publico e privado da classe.

### ISSUE THREAD

**Issue by zabaala** [andersonn-roberto/laravel-sso-test#2]
https://github.com/andersonn-roberto/laravel-sso-test/blob/2e9205bad0cda82d34fa8e5eb13e28b6fdfbee75/client/app/Http/Controllers/Auth/LoginController.php#L47

**Comment by andersonn-roberto** [comment]
Eis o retorno:
```
Client1Broker {#191 ▼
  #url: "http://www.server.dev"
  +broker: "12345"
  #secret: "abc123"
  +token: "84bvsvcmjf48kkgko80ko4w4w"
  #userinfo: null
  #cookie_lifetime: 3600
}
```

**Comment by zabaala** [comment]
Pois é. Como havia lhe dito no inbox, o problema estava relacionado à visibilidade do método.
